### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by alex-chan** [FacePlusPlus/facepp-ios-sdk#8]
在xcode 6.3.2中出现如下错误：
<pre><code>
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FaceppAPI", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code></pre>

**Comment by yangmu266** [comment]
目前sdk不支持模拟器运行

**Comment by alex-chan** [comment]
在真机出现 Undefined symbols for architecture arm64, 将代码目录重新组织后(全放在同一目录) 此问题消失。
